### ISSUE TITLE
can't compile in nginx 1.6.2

### ISSUE THREAD

**Issue by xianhuawei** [cubicdaiya/ngx_dynamic_upstream#4]
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c: In function ‘ngx_dynamic_upstream_get_zone’:
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:76: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:77: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
cc1: warnings being treated as errors
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: left-hand operand of comma expression has no effect
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: value computed is not used
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: left-hand operand of comma expression has no effect
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:78: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c: In function ‘ngx_dynamic_upstream_create_response_buf’:
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:96: error: ‘ngx_http_upstream_rr_peer_t’ has no member named ‘next’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c: In function ‘ngx_dynamic_upstream_handler’:
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:172: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
/tmp/ngx_dynamic_upstream-master//src/ngx_dynamic_upstream_module.c:186: error: ‘ngx_http_upstream_srv_conf_t’ has no member named ‘shm_zone’
make: **\* [objs/src/src/ngx_dynamic_upstream_module.o] Error 1

**Comment by cubicdaiya** [comment]
`ngx_dynamic_upstream` is available from nginx-1.9.0. Please see the [README.md](https://github.com/cubicdaiya/ngx_dynamic_upstream#requirements) for details.
